version: '3.8'

# services - here i am going to list containers that i want to build
# each service, actually describes a docker run command
services:
  database:
    container_name: vacations-are-us-db-compose
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=vacations_are_us_dbdocker
      - MYSQL_TCP_PORT=3306
    ports:
      - "3309:3306"
    build: ./database
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  backend:
    container_name: vacations-are-us-backend-compose
    environment:
      - NODE_ENV=compose
    ports:
      - "3020:3000"
    build: ./backend
    depends_on:
      database:
        condition: service_healthy

  io:
    container_name: vacations-are-us-io-compose
    ports:
      - "3022:3004"
    build: ./io

  frontend:
    container_name: vacations-are-us-frontend-compose
    ports: 
      - 3012:80
    build:
      context: ./frontend
      dockerfile: Dockerfile.compose


  localstack:
    container_name: vacations-are-us-localstack-compose
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    image: localstack/localstack
    volumes:
      - s3localdata:/var/lib/localstack

volumes:
  s3localdata:
  mysql_data:
